import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/now" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.typekit.net/fxw5jnj.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
